apiVersion: v1
kind: Pod
metadata:
  name: ngnix
  labels:
    name: ngnix
spec:
  containers:
  - name: sample-pod
    image: userxy2015/ngnix
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
