apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: 5
  selector:
    app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
        env: test
    spec:
      containers:
        - name: myapp
          image: tomcat:9.0
          ports:
            - containerPort: 80
